// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Player struct {
	ID           int64
	Name         string
	MyclubID     int64
	RunPower     float64
	BallHandling float64
	IsGoalie     bool
}
