// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Player struct {
	ID           int64
	Name         string
	MyclubID     int64
	RunPower     float64
	BallHandling float64
	IsGoalie     bool
}

type Practice struct {
	ID   int64
	Date time.Time
}

type PracticePlayer struct {
	PracticeID int64
	PlayerID   int64
	TeamNumber int64
}
