// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Player struct {
	ID           int64
	Name         string
	MyclubID     int64
	RunPower     float64
	BallHandling float64
	IsGoalie     bool
}

type Practice struct {
	ID   int64
	Date time.Time
}

type PracticePlayer struct {
	PracticeID int64
	PlayerID   int64
	TeamNumber int64
}

type User struct {
	ID             int64
	Username       string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UserSession struct {
	SessionID string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
	DeletedAt sql.NullTime
}
