// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
)

const addPlayer = `-- name: AddPlayer :exec
INSERT INTO
    players (name, myclub_id, run_power, ball_handling)
VALUES
    (?, ?, ?, ?)
`

type AddPlayerParams struct {
	Name         string
	MyclubID     int64
	RunPower     float64
	BallHandling float64
}

func (q *Queries) AddPlayer(ctx context.Context, arg AddPlayerParams) error {
	_, err := q.db.ExecContext(ctx, addPlayer,
		arg.Name,
		arg.MyclubID,
		arg.RunPower,
		arg.BallHandling,
	)
	return err
}

const getActivePlayers = `-- name: GetActivePlayers :many
SELECT
    id,
    name,
    myclub_id,
    run_power,
    ball_handling,
    is_goalie,
    inactivated_at
FROM
    players
WHERE
    inactivated_at is null
`

func (q *Queries) GetActivePlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getActivePlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MyclubID,
			&i.RunPower,
			&i.BallHandling,
			&i.IsGoalie,
			&i.InactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInactivePlayers = `-- name: GetInactivePlayers :many
SELECT
    id,
    name,
    myclub_id,
    run_power,
    ball_handling,
    is_goalie,
    inactivated_at
FROM
    players
WHERE
    inactivated_at is not null
`

func (q *Queries) GetInactivePlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getInactivePlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MyclubID,
			&i.RunPower,
			&i.BallHandling,
			&i.IsGoalie,
			&i.InactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerById = `-- name: GetPlayerById :one
SELECT
    id,
    name,
    myclub_id,
    run_power,
    ball_handling,
    is_goalie,
    inactivated_at
FROM
    players
WHERE
    id = ?
`

func (q *Queries) GetPlayerById(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerById, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MyclubID,
		&i.RunPower,
		&i.BallHandling,
		&i.IsGoalie,
		&i.InactivatedAt,
	)
	return i, err
}

const getPlayerByMyclubID = `-- name: GetPlayerByMyclubID :one
SELECT
    id,
    name,
    myclub_id,
    run_power,
    ball_handling,
    is_goalie,
    inactivated_at
FROM
    players
WHERE
    myclub_id = ?
`

func (q *Queries) GetPlayerByMyclubID(ctx context.Context, myclubID int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByMyclubID, myclubID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MyclubID,
		&i.RunPower,
		&i.BallHandling,
		&i.IsGoalie,
		&i.InactivatedAt,
	)
	return i, err
}

const isExistingPlayer = `-- name: IsExistingPlayer :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            players
        WHERE
            myclub_id = ?
    )
`

func (q *Queries) IsExistingPlayer(ctx context.Context, myclubID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isExistingPlayer, myclubID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setPlayerActive = `-- name: SetPlayerActive :exec
UPDATE players
SET
    inactivated_at = NULL
WHERE
    id = ?
`

func (q *Queries) SetPlayerActive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setPlayerActive, id)
	return err
}

const setPlayerInactive = `-- name: SetPlayerInactive :exec
UPDATE players
SET
    inactivated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

func (q *Queries) SetPlayerInactive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setPlayerInactive, id)
	return err
}

const updatePlayerAttributes = `-- name: UpdatePlayerAttributes :one
UPDATE players
SET
    run_power = ?,
    ball_handling = ?,
    is_goalie = ?
WHERE
    id = ? RETURNING id,
    name,
    myclub_id,
    run_power,
    ball_handling,
    is_goalie,
    inactivated_at
`

type UpdatePlayerAttributesParams struct {
	RunPower     float64
	BallHandling float64
	IsGoalie     bool
	ID           int64
}

func (q *Queries) UpdatePlayerAttributes(ctx context.Context, arg UpdatePlayerAttributesParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerAttributes,
		arg.RunPower,
		arg.BallHandling,
		arg.IsGoalie,
		arg.ID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MyclubID,
		&i.RunPower,
		&i.BallHandling,
		&i.IsGoalie,
		&i.InactivatedAt,
	)
	return i, err
}
