// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
)

const addPlayer = `-- name: AddPlayer :exec
INSERT INTO
    players (name, myclub_id, run_power, ball_handling)
VALUES
    (?, ?, ?, ?)
`

type AddPlayerParams struct {
	Name         string
	MyclubID     int64
	RunPower     float64
	BallHandling float64
}

func (q *Queries) AddPlayer(ctx context.Context, arg AddPlayerParams) error {
	_, err := q.db.ExecContext(ctx, addPlayer,
		arg.Name,
		arg.MyclubID,
		arg.RunPower,
		arg.BallHandling,
	)
	return err
}

const getAllPlayers = `-- name: GetAllPlayers :many
SELECT
    id,
    name,
    myclub_id,
    run_power,
    ball_handling,
    is_goalie
FROM
    players
`

func (q *Queries) GetAllPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MyclubID,
			&i.RunPower,
			&i.BallHandling,
			&i.IsGoalie,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerByMyclubID = `-- name: GetPlayerByMyclubID :one
SELECT
    id,
    name,
    myclub_id,
    run_power,
    ball_handling,
    is_goalie
FROM
    players
WHERE
    myclub_id = ?
`

func (q *Queries) GetPlayerByMyclubID(ctx context.Context, myclubID int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByMyclubID, myclubID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MyclubID,
		&i.RunPower,
		&i.BallHandling,
		&i.IsGoalie,
	)
	return i, err
}

const isExistingPlayer = `-- name: IsExistingPlayer :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            players
        WHERE
            myclub_id = ?
    )
`

func (q *Queries) IsExistingPlayer(ctx context.Context, myclubID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isExistingPlayer, myclubID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const toggleGoalieStatus = `-- name: ToggleGoalieStatus :exec
UPDATE players
SET
    is_goalie = ?
WHERE
    id = ?
`

type ToggleGoalieStatusParams struct {
	IsGoalie bool
	ID       int64
}

func (q *Queries) ToggleGoalieStatus(ctx context.Context, arg ToggleGoalieStatusParams) error {
	_, err := q.db.ExecContext(ctx, toggleGoalieStatus, arg.IsGoalie, arg.ID)
	return err
}

const updatePlayerRunPower = `-- name: UpdatePlayerRunPower :exec
UPDATE players
SET
    run_power = ?
WHERE
    myclub_id = ?
`

type UpdatePlayerRunPowerParams struct {
	RunPower float64
	MyclubID int64
}

func (q *Queries) UpdatePlayerRunPower(ctx context.Context, arg UpdatePlayerRunPowerParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerRunPower, arg.RunPower, arg.MyclubID)
	return err
}
