// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: practices.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addPlayerToPractice = `-- name: AddPlayerToPractice :exec
INSERT INTO
    practice_players (practice_id, player_id, team_number)
VALUES
    (?, ?, ?)
`

type AddPlayerToPracticeParams struct {
	PracticeID int64
	PlayerID   int64
	TeamNumber int64
}

func (q *Queries) AddPlayerToPractice(ctx context.Context, arg AddPlayerToPracticeParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToPractice, arg.PracticeID, arg.PlayerID, arg.TeamNumber)
	return err
}

const createPractice = `-- name: CreatePractice :execlastid
INSERT INTO
    practices (date)
VALUES
    (?) RETURNING id
`

func (q *Queries) CreatePractice(ctx context.Context, date time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPractice, date)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getNewestPractices = `-- name: GetNewestPractices :many
SELECT
    id, date
FROM
    practices
ORDER BY
    date DESC
LIMIT
    ?
`

func (q *Queries) GetNewestPractices(ctx context.Context, limit int64) ([]Practice, error) {
	rows, err := q.db.QueryContext(ctx, getNewestPractices, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Practice
	for rows.Next() {
		var i Practice
		if err := rows.Scan(&i.ID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPracticePlayer = `-- name: GetPracticePlayer :one
SELECT
    practice_id,
    player_id,
    team_number,
    has_vest
FROM
    practice_players
WHERE
    practice_id = ?
    AND player_id = ?
`

type GetPracticePlayerParams struct {
	PracticeID int64
	PlayerID   int64
}

func (q *Queries) GetPracticePlayer(ctx context.Context, arg GetPracticePlayerParams) (PracticePlayer, error) {
	row := q.db.QueryRowContext(ctx, getPracticePlayer, arg.PracticeID, arg.PlayerID)
	var i PracticePlayer
	err := row.Scan(
		&i.PracticeID,
		&i.PlayerID,
		&i.TeamNumber,
		&i.HasVest,
	)
	return i, err
}

const getPracticeWithPlayers = `-- name: GetPracticeWithPlayers :many
SELECT
    pr.id as practice_id,
    pr.date,
    pp.team_number,
    pp.has_vest,
    pl.id as player_id,
    pl.myclub_id,
    pl.name,
    pl.run_power,
    pl.ball_handling,
    pl.is_goalie
FROM
    practice_players pp
    LEFT JOIN practices pr ON pr.id = pp.practice_id
    LEFT JOIN players pl ON pl.id = pp.player_id
WHERE
    pr.id = ?
`

type GetPracticeWithPlayersRow struct {
	PracticeID   sql.NullInt64
	Date         sql.NullTime
	TeamNumber   int64
	HasVest      bool
	PlayerID     sql.NullInt64
	MyclubID     sql.NullInt64
	Name         sql.NullString
	RunPower     sql.NullFloat64
	BallHandling sql.NullFloat64
	IsGoalie     sql.NullBool
}

func (q *Queries) GetPracticeWithPlayers(ctx context.Context, id int64) ([]GetPracticeWithPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getPracticeWithPlayers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPracticeWithPlayersRow
	for rows.Next() {
		var i GetPracticeWithPlayersRow
		if err := rows.Scan(
			&i.PracticeID,
			&i.Date,
			&i.TeamNumber,
			&i.HasVest,
			&i.PlayerID,
			&i.MyclubID,
			&i.Name,
			&i.RunPower,
			&i.BallHandling,
			&i.IsGoalie,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayerTeam = `-- name: SetPlayerTeam :exec
UPDATE practice_players
SET
    team_number = ?
WHERE
    practice_id = ?
    AND player_id = ?
`

type SetPlayerTeamParams struct {
	TeamNumber int64
	PracticeID int64
	PlayerID   int64
}

func (q *Queries) SetPlayerTeam(ctx context.Context, arg SetPlayerTeamParams) error {
	_, err := q.db.ExecContext(ctx, setPlayerTeam, arg.TeamNumber, arg.PracticeID, arg.PlayerID)
	return err
}

const togglePracticePlayerVest = `-- name: TogglePracticePlayerVest :exec
UPDATE practice_players
SET
    has_vest = ?
WHERE
    practice_id = ?
    AND player_id = ?
`

type TogglePracticePlayerVestParams struct {
	HasVest    bool
	PracticeID int64
	PlayerID   int64
}

func (q *Queries) TogglePracticePlayerVest(ctx context.Context, arg TogglePracticePlayerVestParams) error {
	_, err := q.db.ExecContext(ctx, togglePracticePlayerVest, arg.HasVest, arg.PracticeID, arg.PlayerID)
	return err
}
