// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: practices.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addPlayerToPractice = `-- name: AddPlayerToPractice :exec
INSERT INTO practice_players (practice_id, player_id, team_number)
VALUES (?,?,?)
`

type AddPlayerToPracticeParams struct {
	PracticeID int64
	PlayerID   int64
	TeamNumber int64
}

func (q *Queries) AddPlayerToPractice(ctx context.Context, arg AddPlayerToPracticeParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToPractice, arg.PracticeID, arg.PlayerID, arg.TeamNumber)
	return err
}

const createPractice = `-- name: CreatePractice :execresult
INSERT INTO practices (date)
VALUES (?)
RETURNING id
`

func (q *Queries) CreatePractice(ctx context.Context, date time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPractice, date)
}
