// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package db

import (
	"context"
	"time"
)

const endUserSession = `-- name: EndUserSession :exec
UPDATE user_sessions
SET
    deleted_at = CURRENT_TIMESTAMP
WHERE
    session_id = ?
    AND deleted_at is null
`

func (q *Queries) EndUserSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, endUserSession, sessionID)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
    session_id, user_id, expires_at, created_at, deleted_at
FROM
    user_sessions
WHERE
    session_id = ?
    AND expires_at > CURRENT_TIMESTAMP
    AND deleted_at IS NULL
`

func (q *Queries) GetActiveSession(ctx context.Context, sessionID string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, sessionID)
	var i UserSession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const startUserSession = `-- name: StartUserSession :one
INSERT INTO
    user_sessions (session_id, user_id, expires_at)
VALUES
    (?, ?, ?)
RETURNING
    session_id, user_id, expires_at, created_at, deleted_at
`

type StartUserSessionParams struct {
	SessionID string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) StartUserSession(ctx context.Context, arg StartUserSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, startUserSession, arg.SessionID, arg.UserID, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
